language: java
jdk: openjdk8
os: linux

before_install:
  - sudo apt-get install -y p7zip-full
  - cd ..
  - wget http://s3.amazonaws.com/fractalsoftworks/starsector/starsector_linux-0.9a-RC10.zip
  - unzip starsector_linux*
  - mv mayorate starsector/mods
  - cd starsector/mods/mayorate
  - util/fetch-deps.sh

script:
  - ./gradlew build

notifications:
  email: false
